import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'

export default function Timeline({ userName }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Time Line </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1> Time Line of {userName} </h1>
        <Link href="/"> go home </Link>
      </main>

    </div>
  )
}

Timeline.getInitialProps = () => {
  return fetch('http://localhost:3000/api/hello')
  .then(res => res.json())
}
