import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Timeline from './timeline'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Terra Futuro </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         ¡Bienvenido a  <a href="https://nextjs.org">TerraFuturo!</a>
        </h1>
        <nav className={styles.nav}>
          <Link href="/timeline">
          time line
          </Link>
        </nav>
      </main>

    </div>
  )
}

